name: Build and test

on: [push]

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      # https://github.com/gradle/gradle-build-action
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Gradle assemble
        run: ./gradlew assemble
      - name: Check code style
        run: ./gradlew ktlintCheck
      - name: Docker Compose up
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
          down-flags: "--volumes"
      - name: Gradle Build
        run: ./gradlew build
      - name: Generate kover coverage report
        run: ./gradlew koverXmlReport
      - name: Add coverage report to PR
        id: kover
        uses: mi-kas/kover-report@v1
        with:
          path: ${{ github.workspace }}/build/reports/kover/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          title: Code Coverage
          update-comment: true
          min-coverage-overall: 80
          min-coverage-changed-files: 80
          coverage-counter-type: LINE