name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # https://github.com/marketplace/actions/deploy-to-heroku
      - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "agilogy-time-tracking"
          heroku_email: "jordi.pradel@agilogy.com"
          branch: main
          dontautocreate: true
          usedocker: true
          docker_heroku_process_type: web
          healthcheck: "https://agilogy-time-tracking.herokuapp.com/health"
          checkstring: "OK"
          delay: 5

